spring:
  application:
    name: Stockfy

  devtools:
    remote:
      secret: 123

  docker:
    compose:
      lifecycle-management: start-and-stop
      readiness:
        tcp:
          connect-timeout: 10s
          read-timeout: 5s
        timeout: 1m
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true