spring.application.name=stockfy

# Profile Configuration
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
stockfy.users.reset-code-hash-secret=${stockfy.security.hmac.secret}
