spring:
  application:
    name: Stockfy
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  messages:
    basename:
      - messages
    encoding: UTF-8
    common-messages: "classpath:messages.properties"
    fallback-to-system-locale: false
