spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          time_zone: America/Sao_Paulo
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  docker:
    compose:
      enabled: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

# Environment variables
payment-service:
  refund-max-days: ${REFUND_MAX_DAYS}

jwt:
  secret: ${JWT_SECRET}
  expire-days: ${JWT_EXPIRE_DAYS}
  expire-hours: ${JWT_EXPIRE_HOURS}
  expire-minutes: ${JWT_EXPIRE_MINUTES}

refresh-token:
  expire-days: ${REFRESH_TOKEN_EXPIRE_DAYS}

owner:
  full-name: ${OWNER_FULL_NAME}
  cpf: ${OWNER_CPF}
  birthday: ${OWNER_BIRTHDAY}
  password: ${OWNER_PASSWORD}
  role: ${OWNER_ROLE}
  contact:
    email: ${OWNER_EMAIL}
    phone-number: ${OWNER_PHONE_NUMBER}
  address:
    street: ${OWNER_ADDRESS_STREET}
    number: ${OWNER_ADDRESS_NUMBER}
    complement: ${OWNER_ADDRESS_COMPLEMENT}
    neighborhood: ${OWNER_ADDRESS_NEIGHBORHOOD}
    city: ${OWNER_ADDRESS_CITY}
    state: ${OWNER_ADDRESS_STATE}
    zip-code: ${OWNER_ADDRESS_ZIP_CODE}
    country: ${OWNER_ADDRESS_COUNTRY}
