services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: stockfy-app-prod
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/stockfy_db
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      PAYMENT_SERVICE_REFUND_MAX_DAYS: ${REFUND_MAX_DAYS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_DAYS: ${JWT_EXPIRE_DAYS}
      JWT_EXPIRE_HOURS: ${JWT_EXPIRE_HOURS}
      JWT_EXPIRE_MINUTES: ${JWT_EXPIRE_MINUTES}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      OWNER_FULL_NAME: ${OWNER_FULL_NAME}
      OWNER_CPF: ${OWNER_CPF}
      OWNER_BIRTHDAY: ${OWNER_BIRTHDAY}
      OWNER_PASSWORD: ${OWNER_PASSWORD}
      OWNER_ROLE: ${OWNER_ROLE}
      OWNER_EMAIL: ${OWNER_EMAIL}
      OWNER_PHONE_NUMBER: ${OWNER_PHONE_NUMBER}
      OWNER_ADDRESS_STREET: ${OWNER_ADDRESS_STREET}
      OWNER_ADDRESS_NUMBER: ${OWNER_ADDRESS_NUMBER}
      OWNER_ADDRESS_COMPLEMENT: ${OWNER_ADDRESS_COMPLEMENT}
      OWNER_ADDRESS_NEIGHBORHOOD: ${OWNER_ADDRESS_NEIGHBORHOOD}
      OWNER_ADDRESS_CITY: ${OWNER_ADDRESS_CITY}
      OWNER_ADDRESS_STATE: ${OWNER_ADDRESS_STATE}
      OWNER_ADDRESS_ZIP_CODE: ${OWNER_ADDRESS_ZIP_CODE}
      OWNER_ADDRESS_COUNTRY: ${OWNER_ADDRESS_COUNTRY}